version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            git submodule init
            git submodule update
            npm install
            npm run build
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            npm run test.coverage
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
workflows:
    build-and-test:
      jobs:
        - build-and-test
