version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: git submodule init
      - run: git submodule update
      - run: npm install
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
