version: 2.1
jobs:
  build-and-test:
    build:
      docker:
        - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test
